package org.mdedetrich.webmodels

trait ResponseHeaders {
  val `Access-Control-Allow-Origin`: String = "Access-Control-Allow-Origin"
  val `Accept-Patch`: String                = "Accept-Patch"
  val `Accept-Ranges`: String               = "Accept-Ranges"
  val `Age`: String                         = "Age"
  val `Allow`: String                       = "Allow"
  val `Alt-Svc`: String                     = "Alt-Svc"
  val `Cache-Control`: String               = "Cache-Control"
  val `Connection`: String                  = "Connection"
  val `Content-Disposition`: String         = "Content-Disposition"
  val `Content-Encoding`: String            = "Content-Encoding"
  val `Content-Language`: String            = "Content-Language"
  val `Content-Length`: String              = "Content-Length"
  val `Content-Location`: String            = "Content-Location"
  val `Content-MD5`: String                 = "Content-MD5"
  val `Content-Range`: String               = "Content-Range"
  val `Content-Security-Policy`: String     = "Content-Security-Policy"
  val `Content-Type`: String                = "Content-Type"
  val `Date`: String                        = "Date"
  val `ETag`: String                        = "ETag"
  val `Expires`: String                     = "Expires"
  val `Last-Modified`: String               = "Last-Modified"
  val `Link`: String                        = "Link"
  val `Location`: String                    = "Location"
  val `P3P`: String                         = "P3P"
  val `Pragma`: String                      = "Pragma"
  val `Proxy-Authenticate`: String          = "Proxy-Authenticate"
  val `Public-Key-Pins`: String             = "Public-Key-Pins"
  val `Refresh`: String                     = "Refresh"
  val `Retry-After`: String                 = "Retry-After"
  val `Server`: String                      = "Server"
  val `Set-Cookie`: String                  = "Set-Cookie"
  val `Status`: String                      = "Status"
  val `Strict-Transport-Security`: String   = "Strict-Transport-Security"
  val `Trailer`: String                     = "Trailer"
  val `Transfer-Encoding`: String           = "Transfer-Encoding"
  val `TSV`: String                         = "TSV"
  val `Upgrade`: String                     = "Upgrade"
  val `Upgrade-Insecure-Requests`: String   = "Upgrade-Insecure-Requests"
  val `Vary`: String                        = "Vary"
  val `Via`: String                         = "Via"
  val `Warning`: String                     = "Warning"
  val `WWW-Authenticate`: String            = "WWW-Authenticate"
  val `X-Content-Duration`: String          = "X-Content-Duration"
  val `X-Content-Security-Policy`: String   = "X-Content-Security-Policy"
  val `X-Content-Type-Options`: String      = "X-Content-Type-Options"
  val `X-Correlation-ID`: String            = "X-Correlation-ID"
  val `X-Frame-Options`: String             = "X-Frame-Options"
  val `X-Powered-By`: String                = "X-Powered-By"
  val `X-Request-ID`: String                = "X-Request-ID"
  val `X-UA-Compatible`: String             = "X-UA-Compatible"
  val `X-WebKit-CSP`: String                = "X-WebKit-CSP"
  val `X-XSS-Protection`: String            = "X-XSS-Protection"
}

object ResponseHeaders extends ResponseHeaders
